name: example

on:
  - push
  - pull_request

jobs:
  job_name:
    name: test session
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "windows-latest", "macos-latest"]
        python: ["3.11", "3.10", "3.9"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python }}

      - name: print architecture
        run: |
          uname -a

      - name: print python version
        run: |
          python --version
