name: example

on:
  - push
  - pull_request

jobs:
  job_name:
    name: test session
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "windows-latest", "macos-latest"]
        python: ["3.11", "3.10", "3.9"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python }}

      - name: build
        run: |
          mkdir build
          python --version > build/artifact_${{ matrix.python }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built_package
          path: build

  process_artifacts:
    runs-on: ubuntu-latest
    needs: job_name
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: built_package
          path: artifacts_directory

      - name: print artifacts
        run: |
          find artifacts_directory
          find artifacts_directory -exec cat {} \;
