name: example

on:
  - push
  - pull_request

jobs:
  job_name:
    name: test session
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "windows-latest", "macos-latest"]
        python: ["3.11", "3.10", "3.9"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: docker pull python image
        run: |
          docker pull python:${{matrix.python}}-slim

      - name: docker run
        run: |
          docker run python:${{matrix.python}}-slim python --version

      - name: docker login to quay
        run: |
          docker login --username ${{ secrets.QUAY_USERNAME }} --password ${{ secrets.QUAY_TOKEN }} quay.io

      - name: docker push to quay
        run: |
          original_tag="python:${{matrix.python}}-slim"
          new_tag="quay.io/dtrifiro/python:${{matrix.python}}-slim"
          docker tag ${original_tag} ${new_tag}
          docker push ${new_tag}

  # process_artifacts:
  #   runs-on: ubuntu-latest
  #   needs: job_name
  #   steps:
  #     - name: download artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: built_package
  #         path: artifacts_directory

  #     - name: print artifacts
  #       run: |
  #         find artifacts_directory
  #         find artifacts_directory -exec cat {} \;
