name: example

on:
  - push
  - pull_request

jobs:
  job_name:
    name: test session
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: echo hello world
        run: |
          echo "hello world"
